### PR TITLE
fix updateSubMsg

### PR DESCRIPTION
**Pull request by bill-torpey**
> see https://github.com/fquinner/OpenMAMA-omnm/issues/9

something like this?

### CODE REVIEW

**Comment by bill-torpey** [comment]
Note that the updateSubMsg test is failing because Mama is passing a msgPayload, not a mamaMsg.

So this test will never pass until Mama is changed to reflect the (new) convention of passing a mamaMsg as fourth param.  

Please let me know how you want to handle this going forward.  I'm OK with making changes, but we should prob discuss first if that's the way you want to go.

FWIW, I can confirm that all our internal tests pass, and those are pretty robust.

**Comment by fquinner** [comment]
I'll submit fix for mama separately thanks - looks good

**Comment by bill-torpey** [comment]
Hi Frank:

Just curious -- it looks like the change for this hasn't made it into mama yet, is that correct?

I also notice that a similar situation exists with mamaMsg_addMsg, which explicitly calls msgPayloadAddMsg with the payload, not the mamaMsg.

Do you have an idea when omnm and mama will be brought into sync?  It's getting a bit confusing on this end.

Thanks!

Bill

**Comment by fquinner** [comment]
Hi Bill,

Yeah will get around to this one still very much want to see it fixed but just a little lower on the priority list. Currently working through getting java builds working for CI with unit tests and warning free and would like to get C# in the same state, then will burn through the backlog.

Cheers,
Frank

**Pull request merged**
